# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
