# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='action',
            field=models.CharField(choices=[('ДА', 'yes'), ('НЕТ', 'no')], max_length=3, null=True, verbose_name='Акционный?'),
        ),
    ]
