# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='action',
            field=models.CharField(choices=[('Нет', 'Да'), ('Нет', 'Нет')], max_length=3, null=True, verbose_name='Акционный?'),
        ),
    ]
