# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160915_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='app',
            field=models.TextField(blank=True, null=True, verbose_name='Показания к применению и применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True, null=True, verbose_name='Уход'),
        ),
        migrations.AddField(
            model_name='product',
            name='compos',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='sdesc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
    ]
