# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pername', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя заказчика')),
                ('perphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактный телефон')),
                ('peremail', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('prodlist', models.TextField(blank=True, null=True, verbose_name='Заказной лист')),
            ],
        ),
    ]
