# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20160916_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peremail',
            field=models.EmailField(blank=True, default=1, max_length=200, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pername',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Имя заказчика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='perphone',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Контактный телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='prodlist',
            field=models.TextField(blank=True, default=1, verbose_name='Заказной лист'),
            preserve_default=False,
        ),
    ]
