# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20160916_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peremail',
            field=models.EmailField(max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pername',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='perphone',
            field=models.CharField(max_length=200, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prodlist',
            field=models.TextField(null=True, verbose_name='Заказной лист'),
        ),
    ]
